apiVersion: v1
kind: Service
metadata:
  name: hello-world
  #namespace: default
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    #service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  #externalTrafficPolicy: Local
  selector:
    app: hello-world
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30331
